name: ci
on:
  push:
    branches:
      - master
      - ci-test
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [10, 12, 14]
        exclude:
          - os: windows-latest
            node: 10
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: npm install
    - name: Test (Linux)
      if: runner.os == 'Linux'
      run: xvfb-run -a npm test
    - name: Test (macOS, Windows)
      if: runner.os != 'Linux'
      run: npm test
